name: Massimo Sirolla
favicon: null
layout_spectrum: 0.74189
typography_spectrum: 0.20541
title: Loyalzoo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#75b3b5'
    - '#f3f3f4'
    - '#00ffff'
    - '#000000'
    - '#0000ff'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
